### ISSUE TITLE
Last Row in Switch Matrix doesn't work

### ISSUE THREAD

**Issue by foenich** [PPUC/io-boards#3]
I've configured a switch matrix but all the switches that are related to the last row have no effect. All the other switches trigger at least an event (but not always the correct switch number).
This is the config:

```
switchMatrix:
  description: 'SW Matrix'
  board: 1
  activeLow: true
  pulseTime: 2
  columns:
    -
      description: 'SW Matix Col1'
      number: 4
      port: 9
    -
      description: 'SW Matix Col2'
      number: 5
      port: 10
    -
      description: 'SW Matix Col3'
      number: 6
      port: 11
  rows:
    -
      description: 'SW Row 1'
      number: 6
      port: 12
    -
      description: 'SW Row 2'
      number: 7
      port: 13
    -
      description: 'SW Row 3'
      number: 8
      port: 14

```
